version: 2.1
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build Docker image
          command: |
            docker build -t smart-brain-x1-dockerize:circleci .
            docker images
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Pushing to heroku registry
          command: |
            heroku container:login
            heroku container:push web --arg NODE_ENV=production -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master